version: '3.4'

services:
  cloudsalessystem.api:
    image: ${DOCKER_REGISTRY-}cloudsalessystemapi
    build:
      context: .
      dockerfile: src/CloudSalesSystem.Api/Dockerfile

  cloud-sales-system-db:
    image: postgres:latest
    container_name: CloudSalesSystem.Db
    environment:
      - POSTGRES_DB=cloud-sales-system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./.containers/seq:/data
