global using Xunit;
global using System.Reflection;
global using CloudSalesSystem.Application.Paging;
global using CloudSalesSystem.Domain.Abstractions;
global using CloudSalesSystem.Infrastructure;
global using FluentAssertions;
global using NetArchTest.Rules;
global using FluentValidation;
global using MediatR;